using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using javacc.net;
namespace org.javacc.parser;

public class JavaCCGlobals 
{
	protected internal const string toolName = "JavaCC";

	public static string fileName;

	public static string origFileName;

	public static bool jjtreeGenerated;

	public static ArrayList toolNames;

	public static string cu_name;

	public static ArrayList cu_to_insertion_point_1;

	public static ArrayList cu_to_insertion_point_2;

	public static ArrayList cu_from_insertion_point_2;

	public static List<NormalProduction> bnfproductions;

	public static Hashtable production_table;

	public static Dictionary<string,int> lexstate_S2I;

	public static Hashtable lexstate_I2S;

	public static ArrayList token_mgr_decls;

	public static List<TokenProduction> rexprlist;

	public static int tokenCount;

	public static Hashtable named_tokens_table;

	public static ArrayList ordered_named_tokens;

	public static Hashtable names_of_tokens;

	public static Hashtable rexps_of_tokens;

	public static Hashtable simple_tokens_table;

	protected internal static int maskindex;

	protected internal static int jj2index;

	protected internal static ArrayList maskVals;

	internal static Action actForEof;

	internal static string nextStateForEof;

	protected internal static int cline;

	protected internal static int ccol;

	
	
	public static string getIdString(ArrayList l, string str)
	{
		string str2 = "Generated By:";
		int i;
		for (i = 0; i < l.Count - 1; i++)
		{
			str2 = new StringBuilder().Append(str2).Append((string)l[i]).Append("&")
				.ToString();
		}
		str2 = new StringBuilder().Append(str2).Append((string)l[i]).Append(":")
			.ToString();
		if (str2.Length > 200)
		{
			Console.WriteLine("Tool names too long.");
			
			throw new System.Exception();
		}
		string result = new StringBuilder().Append(str2).Append(" Do not edit this line. ").Append(addUnicodeEscapes(str))
			.ToString();
		
		return result;
	}

	
	public static string addUnicodeEscapes(string str)
	{
		string text = "";
		for (int i = 0; i < str.Length; i++)
		{
			int num = str[i];
			if (num < 32 || num > 126)
			{
				string @this = new StringBuilder().Append("0000").Append(Utils.ToString(num, 16)).ToString();
				text = new StringBuilder().Append(text).Append("\\u").Append(@this.Substring(@this.Length - 4, @this.Length))
					.ToString();
			}
			else
			{
				text = new StringBuilder().Append(text).Append((char)num).ToString();
			}
		}
		return text;
	}

	
	public static ArrayList getToolNames(string str)
	{
		char[] array = new char[256];
		StreamReader fileReader = null;
		int num = 0;
		ArrayList result;
		try
		{
			try
			{
				try
				{
					fileReader = new StreamReader(str);
					int num2;
					while ((num2 = fileReader.Read(array, num, (int)((nint)array.LongLength - num))) != -1 && (nint)(num += num2) != (nint)array.LongLength)
					{
					}
					result = makeToolNameVector(new string(array, 0, num));
				}
				catch (FileNotFoundException)
				{
					goto IL_006d;
				}
			}
			catch (IOException)
			{
				goto IL_0070;
			}
		}
		catch
		{
			//try-fault
			if (fileReader != null)
			{
				try
				{
					fileReader.Close();
				}
				catch (System.Exception x)
				{
					goto IL_0064;
				}
			}
			goto end_IL_0049;
			IL_0064:
			
			end_IL_0049:
			throw;
		}
		if (fileReader != null)
		{
			try
			{
				fileReader.Close();
				return result;
			}
			catch (System.Exception x2)
			{
			}
			
		}
		return result;
		IL_0070:
		//IOException ex3 = null;
		ArrayList result2;
		try
		{
			if (num > 0)
			{
				result2 = makeToolNameVector(new string(array, 0, num));
				goto IL_010b;
			}
		}
		catch
		{
			//try-fault
			if (fileReader != null)
			{
				try
				{
					fileReader.Close();
				}
				catch (System.Exception x3)
				{
					goto IL_0100;
				}
			}
			goto end_IL_00e5;
			IL_0100:
			
			end_IL_00e5:
			throw;
		}
		if (fileReader != null)
		{
			try
			{
				fileReader.Close();
			}
			catch (System.Exception x4)
			{
				goto IL_014a;
			}
		}
		goto IL_0152;
		IL_00b9:
		
		goto IL_0152;
		IL_0152:
		return new ArrayList();
		IL_014a:
		
		goto IL_0152;
		IL_010b:
		if (fileReader != null)
		{
			try
			{
				fileReader.Close();
				return result2;
			}
			catch (System.Exception x5)
			{
			}
			
		}
		return result2;
		IL_006d:
		
		if (fileReader != null)
		{
			try
			{
				fileReader.Close();
			}
			catch (System.Exception x6)
			{
				goto IL_00b9;
			}
		}
		goto IL_0152;
	}

	
	private static ArrayList makeToolNameVector(string P_0)
	{
		ArrayList vector = new ArrayList();
		int num = P_0.IndexOf((char)10);
		if (num == -1)
		{
			num = 1000;
		}
		int num2 = P_0.IndexOf((char)13);
		if (num2 == -1)
		{
			num2 = 1000;
		}
		int num3 = ((num >= num2) ? num2 : num);
		string @this = ((num3 != 1000) ? P_0.Substring(0, num3) : P_0);
		if (@this.IndexOf((char)58) == -1)
		{
			return vector;
		}
		@this = @this.Substring(@this.IndexOf((char) 58) + 1);
		if (@this.IndexOf((char) 58) == -1)
		{
			return vector;
		}
		@this = @this.Substring(0, (@this.IndexOf((char) 58)));
		_ = 0;
		int num4 = 0;
		int num5;
		while (num4 < @this.Length && ((num5 = @this.IndexOf((char) 38, num4)) != -1))
		{
			vector.Add(@this.Substring( num4, num5));
			num4 = num5 + 1;
		}
		if (num4 < @this.Length)
		{
			vector.Add(@this.Substring(num4));
		}
		return vector;
	}

	
	protected internal static void printTokenOnly(Token t, TextWriter pw)
	{
		while (cline < t.BeginLine)
		{
			pw.WriteLine("");
			ccol = 1;
			cline++;
		}
		while (ccol < t.BeginColumn)
		{
			pw.Write(" ");
			ccol++;
		}
		if (t.kind == 90 || t.kind == 89)
		{
			pw.Write(addUnicodeEscapes(t.image));
		}
		else
		{
			pw.Write(t.image);
		}
		cline = t.endLine;
		ccol = t.endColumn + 1;
		int num = t.image[(t.image.Length) - 1];
		if (num == 10 || num == 13)
		{
			cline++;
			ccol = 1;
		}
	}

	
	protected internal static string printLeadingComments(Token t)
	{
		string text = "";
		if (t.specialToken == null)
		{
			return text;
		}
		Token token = t.specialToken;
		while (token.specialToken != null)
		{
			token = token.specialToken;
		}
		while (token != null)
		{
			text = new StringBuilder().Append(text).Append(printTokenOnly(token)).ToString();
			token = token.next;
		}
		if (ccol != 1 && cline != t.BeginLine)
		{
			text = new StringBuilder().Append(text).Append("\n").ToString();
			cline++;
			ccol = 1;
		}
		return text;
	}

	
	protected internal static string printTokenOnly(Token t)
	{
		string str = "";
		while (cline < t.BeginLine)
		{
			str = new StringBuilder().Append(str).Append("\n").ToString();
			ccol = 1;
			cline++;
		}
		while (ccol < t.BeginColumn)
		{
			str = new StringBuilder().Append(str).Append(" ").ToString();
			ccol++;
		}
		str = ((t.kind != 90 && t.kind != 89)
			? new StringBuilder().Append(str).Append(t.image).ToString()
			: new StringBuilder().Append(str).Append(addUnicodeEscapes(t.image)).ToString());
		cline = t.endLine;
		ccol = t.endColumn + 1;
		int num = t.image[(t.image.Length) - 1];
		if (num == 10 || num == 13)
		{
			cline++;
			ccol = 1;
		}
		return str;
	}

	
	public JavaCCGlobals()
	{
	}

	
	public static void bannerLine(string str1, string str2)
	{
		Console.Write(new StringBuilder().Append("Java Compiler Compiler Version 4.1d1 (").Append(str1).ToString());
		if (!string.Equals(str2, ""))
		{
			Console.Write(new StringBuilder().Append(" Version ").Append(str2).ToString());
		}
		Console.WriteLine(")");
	}

	
	public static string getIdString(string str1, string str2)
	{
		ArrayList vector = new ArrayList();
		vector.Add(str1);
		string idString = getIdString(vector, str2);
		
		return idString;
	}

	
	public static bool isGeneratedBy(string str1, string str2)
	{
		ArrayList vector = getToolNames(str2);
		for (int i = 0; i < vector.Count; i++)
		{
			if (string.Equals(str1, vector[i]))
			{
				return true;
			}
		}
		return false;
	}

	
	public static void createOutputDir(FileInfo f)
	{
		if (!f.Exists)
		{
			JavaCCErrors.Warning(new StringBuilder().Append("Output directory \"").Append(f).Append("\" does not exist. Creating the directory.")
				.ToString());
			var d = Directory.CreateDirectory(f.FullName);
			if (! d.Exists)
			{
				JavaCCErrors.Semantic_Error(new StringBuilder().Append("Cannot create the output directory : ").Append(f).ToString());
				return;
			}
		}
		if (!new DirectoryInfo(f.FullName).Exists)
		{
			JavaCCErrors.Semantic_Error(new StringBuilder().Append("\"").Append(f).Append(" is not a valid output directory.")
				.ToString());
		}
		else if (f.IsReadOnly)
		{
			JavaCCErrors.Semantic_Error(new StringBuilder().Append("Cannot write to the output output directory : \"").Append(f).Append("\"")
				.ToString());
		}
	}

	
	public static string staticOpt()
	{
		if (Options.getStatic())
		{
			return "static ";
		}
		return "";
	}

	
	public static string add_escapes(string str)
	{
		string text = "";
		for (int i = 0; i < str.Length; i++)
		{
			int num = str[i];
			if (num == 8)
			{
				text = new StringBuilder().Append(text).Append("\\b").ToString();
				continue;
			}
			if (num == 9)
			{
				text = new StringBuilder().Append(text).Append("\\t").ToString();
				continue;
			}
			if (num == 10)
			{
				text = new StringBuilder().Append(text).Append("\\n").ToString();
				continue;
			}
			if (num == 12)
			{
				text = new StringBuilder().Append(text).Append("\\f").ToString();
				continue;
			}
			if (num == 13)
			{
				text = new StringBuilder().Append(text).Append("\\r").ToString();
				continue;
			}
			if (num == 34)
			{
				text = new StringBuilder().Append(text).Append("\\\"").ToString();
				continue;
			}
			if (num == 39)
			{
				text = new StringBuilder().Append(text).Append("\\'").ToString();
				continue;
			}
			switch (num)
			{
			case 92:
				text = new StringBuilder().Append(text).Append("\\\\").ToString();
				break;
			default:
			{
				string @this = new StringBuilder().Append("0000").Append(Utils.ToString(num, 16)).ToString();
				text = new StringBuilder().Append(text).Append("\\u").Append(@this.Substring(@this.Length - 4, @this.Length))
					.ToString();
				break;
			}
			case 32:
			case 33:
			case 34:
			case 35:
			case 36:
			case 37:
			case 38:
			case 39:
			case 40:
			case 41:
			case 42:
			case 43:
			case 44:
			case 45:
			case 46:
			case 47:
			case 48:
			case 49:
			case 50:
			case 51:
			case 52:
			case 53:
			case 54:
			case 55:
			case 56:
			case 57:
			case 58:
			case 59:
			case 60:
			case 61:
			case 62:
			case 63:
			case 64:
			case 65:
			case 66:
			case 67:
			case 68:
			case 69:
			case 70:
			case 71:
			case 72:
			case 73:
			case 74:
			case 75:
			case 76:
			case 77:
			case 78:
			case 79:
			case 80:
			case 81:
			case 82:
			case 83:
			case 84:
			case 85:
			case 86:
			case 87:
			case 88:
			case 89:
			case 90:
			case 91:
			case 93:
			case 94:
			case 95:
			case 96:
			case 97:
			case 98:
			case 99:
			case 100:
			case 101:
			case 102:
			case 103:
			case 104:
			case 105:
			case 106:
			case 107:
			case 108:
			case 109:
			case 110:
			case 111:
			case 112:
			case 113:
			case 114:
			case 115:
			case 116:
			case 117:
			case 118:
			case 119:
			case 120:
			case 121:
			case 122:
			case 123:
			case 124:
			case 125:
			case 126:
				text = new StringBuilder().Append(text).Append((char)num).ToString();
				break;
			}
		}
		return text;
	}

	protected internal static void printTokenSetup(Token t)
	{
		Token token = t;
		while (token.specialToken != null)
		{
			token = token.specialToken;
		}
		cline = token.BeginLine;
		ccol = token.BeginColumn;
	}

	
	protected internal static void printToken(Token t, TextWriter pw)
	{
		Token token = t.specialToken;
		if (token != null)
		{
			while (token.specialToken != null)
			{
				token = token.specialToken;
			}
			while (token != null)
			{
				printTokenOnly(token, pw);
				token = token.next;
			}
		}
		printTokenOnly(t, pw);
	}

	
	protected internal static void printLeadingComments(Token t, TextWriter pw)
	{
		if (t.specialToken != null)
		{
			Token token = t.specialToken;
			while (token.specialToken != null)
			{
				token = token.specialToken;
			}
			while (token != null)
			{
				printTokenOnly(token, pw);
				token = token.next;
			}
			if (ccol != 1 && cline != t.BeginLine)
			{
				pw.WriteLine("");
				cline++;
				ccol = 1;
			}
		}
	}

	
	protected internal static void printTrailingComments(Token t, TextWriter pw)
	{
		if (t.next != null)
		{
			printLeadingComments(t.next);
		}
	}

	
	protected internal static string printToken(Token t)
	{
		string str = "";
		Token token = t.specialToken;
		if (token != null)
		{
			while (token.specialToken != null)
			{
				token = token.specialToken;
			}
			while (token != null)
			{
				str = new StringBuilder().Append(str).Append(printTokenOnly(token)).ToString();
				token = token.next;
			}
		}
		return new StringBuilder().Append(str).Append(printTokenOnly(t)).ToString();
	}

	
	protected internal static string printTrailingComments(Token t)
	{
		if (t.next == null)
		{
			return "";
		}
		string result = printLeadingComments(t.next);
		
		return result;
	}

	
	public static void reInit()
	{
		fileName = null;
		origFileName = null;
		jjtreeGenerated = false;
		toolNames = null;
		cu_name = null;
		cu_to_insertion_point_1 = new ();
		cu_to_insertion_point_2 = new ();
		cu_from_insertion_point_2 = new ();
		bnfproductions = new ();
		production_table = new ();
		lexstate_S2I = new ();
		lexstate_I2S = new ();
		token_mgr_decls = null;
		rexprlist = new ();
		tokenCount = 0;
		named_tokens_table = new ();
		ordered_named_tokens = new();
		names_of_tokens = new();
		rexps_of_tokens = new();
		simple_tokens_table = new();
		maskindex = 0;
		jj2index = 0;
		maskVals = new();
		cline = 0;
		ccol = 0;
		actForEof = null;
		nextStateForEof = null;
	}

	static JavaCCGlobals()
	{
		cu_to_insertion_point_1 = new();
		cu_to_insertion_point_2 = new();
		cu_from_insertion_point_2 = new();
		bnfproductions = new();
		production_table = new();
		lexstate_S2I = new ();
		lexstate_I2S = new();
		rexprlist = new();
		named_tokens_table = new();
		ordered_named_tokens = new();
		names_of_tokens = new();
		rexps_of_tokens = new();
		simple_tokens_table = new();
		maskindex = 0;
		jj2index = 0;
		maskVals = new();
	}
}
